services:
  api:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI
      - PYTHONPATH=/app

  web:
    build: .
    # command: python app.py (default from Dockerfile)
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
